/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2025-05-17

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

#include "stm32f3xx.h"

void pwm_init_tim2(){

  RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
  RCC->AHBENR  |= RCC_AHBENR_GPIOAEN;


  GPIOA->MODER &= ~((3 << (0*2)) | (3 << (1*2)));
  GPIOA->MODER |=  ((2 << (0*2)) | (2 << (1*2)));
  GPIOA->AFR[0] |= (1 << (0*4)) | (1 << (1*4));


  TIM2->PSC = 72;
  TIM2->ARR = 1000;

  TIM2->CCMR1 |= (6 << 4) | (6 << 12);
  TIM2->CCMR1 |= TIM_CCMR1_OC1PE | TIM_CCMR1_OC2PE;

  TIM2->CCR1 = 250;
  TIM2->CCR2 = 750;

  TIM2->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E;

  TIM2->CR1 |= TIM_CR1_CEN;
}
void pwm_init_tim1(){
  RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
  RCC->AHBENR  |= RCC_AHBENR_GPIOAEN;


  GPIOA->MODER &= ~((3 << (0*2)) | (3 << (1*2)));
  GPIOA->MODER |=  ((2 << (0*2)) | (2 << (1*2)));
  GPIOA->AFR[0] |= (1 << (0*4)) | (1 << (1*4));

  TIM1->ARR = 1000;
  TIM1->PSC = 72;
  TIM1->RCR = 5;

  TIM1->CCMR1 |= (6 << 4) | (6 << 12);
  TIM1->CCMR1 |= TIM_CCMR1_OC1PE | TIM_CCMR1_OC2PE;

  TIM1->CCR1 = 250;
  TIM1->CCR2 = 750;

  TIM1->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E;;

  TIM1->CR1 |= TIM_CR1_CEN;
}
void pwm_init_tim3(){
  RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
  RCC->AHBENR  |= RCC_AHBENR_GPIOAEN;


  GPIOA->MODER &= ~((3 << (0*2)) | (3 << (1*2)));
  GPIOA->MODER |=  ((2 << (0*2)) | (2 << (1*2)));
  GPIOA->AFR[0] |= (1 << (0*4)) | (1 << (1*4));

  TIM3->ARR = 1000;
  TIM3->PSC = 72;

  TIM3->CCMR1 |= (6 << 4) | (6 << 12);
  TIM3->CCMR1 |= TIM_CCMR1_OC1PE | TIM_CCMR1_OC2PE;

  TIM3->CCR1 = 250;
  TIM3->CCR2 = 750;

  TIM3->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E;
  TIM3->CR1 |= TIM_CR1_CEN;

}
void pwm_init_tim8(){
  RCC->APB2ENR |= RCC_APB2ENR_TIM8EN;
  RCC->AHBENR  |= RCC_AHBENR_GPIOAEN;


  GPIOA->MODER &= ~((3 << (0*2)) | (3 << (1*2)));
  GPIOA->MODER |=  ((2 << (0*2)) | (2 << (1*2)));
  GPIOA->AFR[0] |= (1 << (0*4)) | (1 << (1*4));

  TIM8->ARR = 1000;
  TIM8->PSC = 72;
  TIM8->RCR = 5;

  TIM8->CCMR1 |= (6 << 4) | (6 << 12);
  TIM8->CCMR1 |= TIM_CCMR1_OC1PE | TIM_CCMR1_OC2PE;

  TIM8->CCR1 = 250;
  TIM8->CCR2 = 750;

  TIM8->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E;
  TIM8->CR1 |= TIM_CR1_CEN;

}
void GPIO_init(){
  RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
  GPIOB->MODER &= ~GPIO_MODER_MODER3_0;
  GPIOB->MODER |= GPIO_MODER_MODER3_0;
}

void USART2_Init() {
  RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
  RCC->AHBENR |= RCC_AHBENR_GPIOAEN;

    GPIOA->MODER &= ~(GPIO_MODER_MODER2 | GPIO_MODER_MODER3);
    GPIOA->MODER |= GPIO_MODER_MODER2_1 | GPIO_MODER_MODER3_1;
    USART2->BRR = SystemCoreClock / 115200;
    GPIOA->AFR[0] |= (7 << 8) | (7 << 12);
    USART2->CR1 = USART_CR1_TE | USART_CR1_RE | USART_CR1_UE;
}




void init_usart() {
    RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
    GPIOA->MODER |= GPIO_MODER_MODER2_1 | GPIO_MODER_MODER3_1;
    GPIOA->AFR[0] |= (7 << 8) | (7 << 12); 

    RCC->APB1ENR |= RCC_APB1ENR_USART2EN; 

    USART2->BRR = SystemCoreClock / 115200;

    USART2->CR1 |= USART_CR1_TE | USART_CR1_RE;
    USART2->CR1 |= USART_CR1_RXNEIE;

    NVIC_EnableIRQ(USART2_IRQn);

    USART2->CR1 |= USART_CR1_UE; 
}
/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

void delay_ms(uint32_t ms); 

int main(void) {
    SystemCoreClockUpdate();
    pwm_init_tim1();
    pwm_init_tim2();
    pwm_init_tim3();
    pwm_init_tim8();
    // Инициализация USART2
    init_usart();

    const char *msg = "USART2 Initialized!\r\n";

    while (*msg) {
        // Передача данных по USART
        while (!(USART2->ISR & USART_ISR_TXE)); 
        USART2->TDR = *msg++;
    }

    uint32_t ii = 0;
      while (1)
      {
           ii++;
      }
}

void delay_ms(uint32_t ms) {
    for (volatile uint32_t i = 0; i < ms * 8000; i++) {
        __NOP();
    }
}

void USART2_IRQHandler(void) {
    if (USART2->ISR & USART_ISR_RXNE) {
        uint8_t data = USART2->RDR;

        (void)data; // чтобы избежать предупреждения о неиспользуемой переменной
    }
}
